[env]
LIBSQLITE3_SYS_USE_PKG_CONFIG = "0"
SQLITE3_STATIC = "0"
SQLITE3_DYNAMIC = "1"
SQLITE3_NO_PKG_CONFIG = "1"

PKG_CONFIG = ""
PKG_CONFIG_PATH = ""
PKG_CONFIG_LIBDIR = ""
PKG_CONFIG_SYSROOT_DIR = ""

LIBSQLITE3_SYS_STATIC = "0"
SQLITE3_LIB_DIR = "/usr/lib"
SQLITE3_INCLUDE_DIR = "/usr/include"
